name: Build Library
run-name: ${{ github.actor }} is building the library ðŸš€
on:
  push:
    branches:
      - '4.*'
    tags:
      - 'tag_*'
      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."      